"""Problem 002
Each new term in the Fibonacci sequence is generated by adding the previous two
terms. By starting with 1 and 2, the first 10 terms will be:
    1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not
exceed four million, find the sum of the even-valued terms.
"""

t2 = 0
t1 = 1
nextTerm = 0
last = 4000000
for i in range(last):
  nextTerm = t1 + t2
  t1 = t2
  t2 = nextTerm
  if nextTerm<last:
    i = nextTerm
    print(nextTerm)
